#!/usr/bin/env sh
# shellcheck disable=2034
set -aefu
EIX_LIMIT_COMPACT=0
COLORSCHEME0=0;
COLORSCHEME1=0;
COLORSCHEME2=0;
COLORSCHEME3=0;

FZF_DEFAULT_OPTS="--ansi --no-sort -m --reverse --cycle --wrap --scroll-off=20 --no-separator \
  --delimiter : -n 1 --accept-nth=1 --info=inline-right  --pointer='>' --prompt='$ ' --marker='+' \
  --margin=0% --padding=0% --border-label-pos=24 --list-border=rounded \
  --preview-border=none --preview-label='Package Info' --preview-window 'top,44%' --preview='equery -N u -i {1}' \
  --color='16,hl:5, current-hl:5, gap-line:8, input-border:5, prompt:5, spinner:5, pointer:5, selected-hl:5, gutter:-1'  \
  --bind 'alt-u:preview:equery -N u -i {1}' --bind 'alt-d:preview:qdepends -qdrpbIQ --color {1}' \
  --bind 'alt-p:toggle-preview' --bind 'alt-h:preview:equery -N m {1}' --bind 'alt-f:preview:equery -N f --tree {1}' \
  --bind 'alt-space:change-preview-window(right,45%|)' "

eix_install() {
FORMAT_ALL_COMPACT="{system}(%{COLOR_CATEGORY_SYSTEM}){else}{profile}(%{COLOR_CATEGORY_PROFILE}){else}{world}\
(%{COLOR_CATEGORY_WORLD}){else}{world_sets}(%{COLOR_CATEGORY_WORLD_SETS}){else}(%{COLOR_CATEGORY}){}{}{}{}\
<category>/(%{COLOR_NORMAL}){marked}(%{COLOR_MARKED_NAME}){else}{world}(%{COLOR_WORLD}){else}{world_sets}\
(%{COLOR_WORLD_SETS}){else}(%{COLOR_NAME}){}{}{}<name>(%{COLOR_RESET}): {*modus=compact}(%{COLOR_NORMAL})\\((%{COLOR_NORMAL_END})\
{havemarkedversion}<markedversions:MARKEDVERSION>; {}{installed}%{INSTALLEDVERSIONS_COMPACT}\
{recommend} -> %{FORMAT_BEST_CHANGE}{}{else}%{FORMAT_BEST_COMPACT}{}(%{COLOR_NORMAL})\\) \
<description>(%{COLOR_NORMAL_END})%{FORMAT_FINISH}"

  eix --color=always --pure-packages --compact -a
}

eix_remove() {
NAMEVERSION="{system}(%{COLOR_CATEGORY_SYSTEM}){else}{profile}(%{COLOR_CATEGORY_PROFILE}){else}{world}\
(%{COLOR_CATEGORY_WORLD}){else}{world_sets}(%{COLOR_CATEGORY_WORLD_SETS}){else}(%{COLOR_CATEGORY}){}{}{}{}\
<category>/(%{COLOR_NORMAL}){marked}(%{COLOR_MARKED_NAME}){else}{world}(%{COLOR_WORLD}){else}{world_sets}\
(%{COLOR_WORLD_SETS}){else}(bold;underline){}{}{}<name>(%{COLOR_RESET}):<version> <description> \n"

  eix --color=always --pure-packages --compact --world --format '<installedversions:NAMEVERSION>'
}

emerge_finder() {
  pkgpick=$(eix_install | fzf --list-label='  Portage Tree  ')
  if [ -z "$pkgpick" ]; then
    exit
  else
  # shellcheck disable=2086
    sudo emerge -v $pkgpick
  fi
  exit
}

emerge_finder_desc() {
  descpkgpick=$(eix_install | fzf --nth=2 --list-label='  Portage Tree  ')
  if [ -z "$descpkgpick" ]; then
    exit
  else
  # shellcheck disable=2086
    sudo emerge -v $descpkgpick
  fi
  exit
}

deselect_finder() {
  unpkgpick="$(eix_remove | fzf \
      --preview='qdepends -qdrpbIQ --color {1}' --list-label='  World File  ')"
  if [ -z "$unpkgpick" ]; then
    exit
  else
  # shellcheck disable=2086
    sudo emerge --ask --deselect $unpkgpick
  fi
  exit
}

usage() {
  echo "invalid flag(s): $OPTARG"
  echo "usgage: efinder <option>"
  echo "available options are"
  echo "none : to interactively search for packages in the portage tree to emerge"
  echo "-d   : to interactively search for packages by description in the portage tree to emerge"
  echo "-u   : to interactively search for packages in your world file to deselect"
  echo "-h   : to show a help message"
  exit 1
}

help_msg() {
  cat << HERE_EOF
  This is an interactive fuzzy finder for portage.

  With no options it will open a finder letting
  you search through the packages available in the portage tree.

  If you use the -u flag it will show the packages in your world file.
  The chosen packages will be removed from the world file by emerge.

  In the emerge script the default preview shows the use flags for the
  currently selected package.
  In the deselect script, the default preview will show the the package's
  dependencies.

  You can selected multiple packages in either mode with the tab key
  then press enter to emerge, or --deslect the chosen packages.

  It uses all the normal fzf key binds with a few extras added.
  alt-p     : will toggle the preview window
  alt-space : will toggle the preview position
  alt-u     : will show use flags in the preview window
  alt-d     : will show dependencies in the preview window
  alt-f     : will list files of installed packages in the preview window
  alt-h     : will show Upstream info in the preview window
  Escape    : if you want to exit without emerging anything

  Available flags:
  none : to interactively search for files in the portage tree to emerge
  -d   : to interactively search for files by description in the portage tree to emerge
  -u   : to interactively search for files in your world file to deselect
  -h   : to show this help message

HERE_EOF
  exit
}

while getopts ":duh" flag; do
  case $flag in
    d) emerge_finder_desc;;
    u) deselect_finder;;
    h) help_msg;;
    \?) usage >&2;;
  esac
done

if [ -n "$OPTIND" ]; then
  emerge_finder
fi
