#!/usr/bin/sh
# shellcheck disable=2034
# shellcheck disable=2086
set -aefu

EIX_LIMIT_COMPACT=0
COLORSCHEME0=0
COLORSCHEME1=0
COLORSCHEME2=0
COLORSCHEME3=0
FZF_DEFAULT_OPTS="+s -m -d : -n 1\
  --color='16,hl:5, current-hl:5, gap-line:8, input-border:5, prompt:5, spinner:5, pointer:5, selected-hl:5, gutter:-1'\
  --ansi\
  --cycle\
  --wrap\
  --accept-nth=1\
  --pointer='>'\
  --prompt='$ '\
  --marker='+'\
  --margin=0%\
  --padding=2%,0%,0%\
  --scroll-off=20\
  --info=inline-right\
  --no-separator\
  --border-label-pos=24\
  --list-border=top\
  --preview-border=none\
  --preview-label='Package Info'\
  --preview-window 'top,54%'\
  --preview='equery -N u -i {1}'\
  --bind 'alt-u:preview:equery -N u -i {1}'\
  --bind 'alt-d:preview:qdepends -qdrpbIQ --color {1}'\
  --bind 'alt-p:toggle-preview'\
  --bind 'alt-h:preview:equery -N m {1}'\
  --bind 'alt-f:preview:equery -N f --tree {1}'\
  --bind 'alt-space:change-preview-window(right,45%|)'"

usage() {
  cat <<-EOF
	usgage: efinder [option]

	A fzf script for portage.

	Options:
	  none              search for files in the portage tree to merge
	  -d, --description search for files by their description to merge
	  -u, --unmerge     search for files in your world file to deselect
	  -h, --help        show a help message

	EOF
  exit 1
}

help_msg() {
  cat <<-EOF
	efinder
	A fzf script for portage.
	
	running efinder with no options opens a fzf menu, of all the packages
	available to you in your portage tree allowing you to select one
  or multiple to merge
	
	the -u option shows the packages in your world file. Allowing you to
	deselect one or multiple
	
	the default preview shows the use flags for the currently selected package.
	When in unmerge mode preview will show the the package's dependencies.
	
	You can selected multiple packages in either mode with the tab key
	then press enter to merge, or --deslect the chosen packages.

	Usgage: efinder [option]

	Options:
	  none              search for files in the portage tree to merge
	  -d, --description search for files by their description to merge
	  -u, --unmerge     search for files in your world file to deselect
	  -h, --help        show this help message

	Keybinds:
	  alt-p             toggle preview window
	  alt-space         toggle preview position
	  alt-u             preview use flags
	  alt-d             preview dependencies
	  alt-f             preview installed files
	  alt-h             preview packaging info
	  Escape            exit without taking any action
	
	EOF
  exit
}

eix_install() {
  FORMAT_ALL_COMPACT="{system}(%{COLOR_CATEGORY_SYSTEM}){else}{profile}(%{COLOR_CATEGORY_PROFILE}){else}{world}\
(%{COLOR_CATEGORY_WORLD}){else}{world_sets}(%{COLOR_CATEGORY_WORLD_SETS}){else}(%{COLOR_CATEGORY}){}{}{}{}\
<category>/(%{COLOR_NORMAL}){marked}(%{COLOR_MARKED_NAME}){else}{world}(%{COLOR_WORLD}){else}{world_sets}\
(%{COLOR_WORLD_SETS}){else}(%{COLOR_NAME}){}{}{}<name>(%{COLOR_RESET}): {*modus=compact}(%{COLOR_NORMAL})\\((%{COLOR_NORMAL_END})\
{havemarkedversion}<markedversions:MARKEDVERSION>; {}{installed}%{INSTALLEDVERSIONS_COMPACT}\
{recommend} -> %{FORMAT_BEST_CHANGE}{}{else}%{FORMAT_BEST_COMPACT}{}(%{COLOR_NORMAL})\\) \
<description>(%{COLOR_NORMAL_END})%{FORMAT_FINISH}"

  eix --color=always --pure-packages --compact -a
}

eix_remove() {
  NAMEVERSION="{system}(%{COLOR_CATEGORY_SYSTEM}){else}{profile}(%{COLOR_CATEGORY_PROFILE}){else}{world}\
(%{COLOR_CATEGORY_WORLD}){else}{world_sets}(%{COLOR_CATEGORY_WORLD_SETS}){else}(%{COLOR_CATEGORY}){}{}{}{}\
<category>/(%{COLOR_NORMAL}){marked}(%{COLOR_MARKED_NAME}){else}{world}(%{COLOR_WORLD}){else}{world_sets}\
(%{COLOR_WORLD_SETS}){else}(bold;underline){}{}{}<name>(%{COLOR_RESET}):<version> <description> \n"

  eix --color=always --pure-packages --compact --world --format '<installedversions:NAMEVERSION>'
}

emerge_finder() {
  pkgpick=$(eix_install | fzf --list-label='  Portage Tree  ')
  if [ -z "$pkgpick" ]; then
    exit
  else
    sudo emerge -av $pkgpick
  fi
  exit
}

emerge_finder_desc() {
  descpkgpick=$(eix_install | fzf --nth=2 --list-label='  Portage Tree  ')
  if [ -z "$descpkgpick" ]; then
    exit
  else
    sudo emerge -av $descpkgpick
  fi
  exit
}

deselect_finder() {
  unpkgpick="$(eix_remove | fzf \
    --preview='qdepends -qdrpbIQ --color {1}' --list-label='  World File  ')"
  if [ -z "$unpkgpick" ]; then
    exit
  else
    sudo emerge --ask --deselect $unpkgpick
  fi
  exit
}

if ! opts=$(getopt -s sh -o 'd,u,h' -l description,unmerge,help -n "efinder" -- "$@"); then
  usage >&2
fi

eval set -- "$opts"
unset opts
_show=
HALP=

while true; do
  case "$1" in
  -d | --description)
    export _show=desc
    break
    ;;
  -u | --unmerge)
    export _show=unmerg
    break
    ;;
  -h | --help)
    export HALP=true
    break
    ;;
  *)
    export _show=default
    break
    ;;
  esac
done

if [ -n "$_show" ]; then
  case "$_show" in
  desc)
    emerge_finder_desc
    ;;
  unmerg)
    deselect_finder
    ;;
  default)
    emerge_finder
    ;;
  *)
    command ...
    ;;
  esac
elif [ -n "$HALP" ]; then
  help_msg
fi
